"""Regression test: the Python rule engine must reproduce the ORIGINAL frontend (UN2.html) JavaScript
engine exactly. tests/fixtures/parity_js_reference.json was generated by running the original
classifyScheme()/readiness()/fundingPath() in Node over parity_cases.json."""
import json
from pathlib import Path
from types import SimpleNamespace

from app.constants import DOCUMENT_TYPES
from app.models import Scheme
from app.seed import SCHEMES
from app.services.eligibility import ProfileSnapshot, classify_scheme
from app.services.funding import funding_path
from app.services.readiness import compute_readiness

FIX = Path(__file__).parent / "fixtures"
CASES = json.loads((FIX / "parity_cases.json").read_text())
REF = json.loads((FIX / "parity_js_reference.json").read_text())
LABEL_TO_SLUG = {v: k for k, v in DOCUMENT_TYPES.items()}
STATUS = {"Eligible": "eligible", "Potentially Eligible": "potentially_eligible", "Not Eligible": "not_eligible"}
SCHEME_OBJS = [Scheme(**d) for d in SCHEMES]


def _num(v):
    return float(v) if v not in (None, "") else None


def _snapshot(p):
    return ProfileSnapshot(
        age=int(p["age"]) if p.get("age") else None, category=p.get("category"), business_type=p.get("businessType"),
        business_stage=p.get("businessStage"), annual_income=_num(p.get("income")), annual_turnover=_num(p.get("turnover")),
        funding_required=_num(p.get("funding")), own_contribution=_num(p.get("ownContribution")), funding_purpose=p.get("purpose"),
    )


def test_python_engine_matches_original_javascript():
    for case in CASES:
        snap, ref = _snapshot(case["p"]), REF[case["name"]]
        app = SimpleNamespace(status=case["app"].lower().replace(" ", "_")) if case["app"] else None
        r = compute_readiness(snap, SCHEME_OBJS, {LABEL_TO_SLUG[d] for d in case["docs"]}, app)

        assert r["overall"] == ref["overall"], case["name"]
        assert {c["key"]: c["score"] for c in r["categories"]} == ref["cats"], case["name"]
        assert r["top_scheme"]["scheme_id"] == ref["top"], case["name"]
        py_items = [[[i["status"], i["text"], i["action"]] for i in c["items"]] for c in r["categories"]]
        assert py_items == ref["texts"], case["name"]
        assert [[s.id, classify_scheme(s, snap).status, classify_scheme(s, snap).pct] for s in SCHEME_OBJS] == \
               [[a, STATUS[b], c] for a, b, c in ref["schemes"]], case["name"]

        path = funding_path(snap.funding_required, SCHEME_OBJS, snap)
        if ref["path"] is None:            # JS returns null when no funding is entered
            assert path == {"total": 0.0, "steps": [], "gap": 0.0}, case["name"]
            continue
        label = {v: k for k, v in STATUS.items()}
        steps = [[f"{s['scheme_name']} ({label[s['eligibility_status']]})" if s["source"] == "scheme" else "Own contribution",
                  s["amount"]] for s in path["steps"]]
        assert steps == ref["path"]["steps"] and path["gap"] == ref["path"]["gap"], case["name"]
